### ISSUE TITLE
add seperate logging for parallel containers

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/falter-repo_builder#14]
Currently the logging for parallel running docker containers gets printed to std. In result, we cannot read the log for a single container, as they get messed up.

It would be really beneficial, to have the logs printed into a seperate file. The file should have the name of the architecture, that gets build by the docker container.

**Comment by pktpls** [comment]
Each build now tee's its output to a file next to the other build artifacts, example: http://firmware.berlin.freifunk.net/feed/1.2.3-snapshot/packages/x86_64/falter/build.log
